### PR TITLE
Implemented localStorage based JWT sessions.  No more cookies.

### PR DESCRIPTION
**Pull request by Panoplos**

### CODE REVIEW

**Comment by yatsu** [comment]
I looked at the code.

I want to get rid of session management from the server. Is it possible?
For example, when I call the API from console, I don't want to call `/auth/signout` every time I finish the request.
With JWT, we can manage the session only in a client. That is a benefit of JWT.

If we drop Passport and implement social auth manually, could it be simpler?

**Comment by Panoplos** [comment]
Actually, the session is not "required". I simply implemented it in case some backends need it. You can see that the tokens generated in the social auth callback are the same as local auth.

**Comment by yatsu** [comment]
OK, but I found the word `session` all over the place.
This implementation looks taking too much effort to pass the empty session to Passport.
Do we really need Passport?

How about using hello.js like this:
https://ole.michelsen.dk/blog/social-signin-spa-jwt-server.html

Or we can probably directly manage OAuth without Passport.

**Comment by Panoplos** [comment]
It is not passing anything to Passport other than the code in the social callback. Sessions may or may not be necessary, depending on the developer's need, IMO. For instance, I am working on a project that interfaces with complex back-end processes on a blockchain. There are several bits of logic where sessions are needed in this case. In the world, not everything is a _functional_ stateless program. ;^)

**Comment by Panoplos** [comment]
I should qualify my last comment: the kao-jwt-session.js logic is not required for authentication to work. We can simply use Passport JWT session with Bearer token. I'll create a quick sessionless branch in my fork to show you.

**Comment by yatsu** [comment]
I want to keep things as simple as possible in this app.
And it must be maintainable by myself :)

(I know that server-side session are required in some cases though.)

I think Passport really shines when we need the traditional server-side session management doesn't it? Otherwise, we must pass `{ session: false }` to every call.

So let me ask the same question again.
When we don't need server-side sessions and cookies, Does Passport still have benefits to us?
Isn't it overkill?

**Comment by Panoplos** [comment]
See: https://github.com/Panoplos/react-apollo-koa-passport-example/tree/sessionless

Yes, using Passport gives you an abstracted interface to OAuth2 providers. No reason to reinvent the wheel. ;^)

**Comment by yatsu** [comment]
I am not trying to reinvent the wheel. Making the auth logic with only JWT and localStorage is very different approach from Passport. I think we can make them simpler.
Also the response JSON format of each social network is different and we must handle them manually even if we use Passport.

It looks like a monkey/banana problem. we just need a banana and don't want to care about monkeys.

**Comment by yatsu** [comment]
I have implemented Github authentication in `no-passport` branch.

I think it is simpler than Passport. we don't need to learn Passport and struggle dropping cookies and session from it.

I have also created a callback page in front-end and Caddy is not required any more.

**Comment by yatsu** [comment]
Hi @Panoplos, thank you for this!

But I would like to go without Passport.
I implemented Github auth in `no-passport` branch with only OAuth2 library, and it was simple and easy enough. You can integrate other social auth same as this. It is also easy to debug, and the code is easy to maintain even for me.

Passport will probably be required when you need sessions and its tight integration to Koa. In this case, you might also want to use cookies instead of JWT because the sessions can be managed in server-side. I guess the first version of your PR is the normal use case of Passport.
But I would rather pick small libraries one by one and keep things as simple as possible in this app.

Feel free to fork the repo and publish your own version!
It would be good if there are multiple options people can choose.

**Comment by yatsu** [comment]
I have merged this into `passport` branch.
Thanks!

**Pull request merged**
