### PR TITLE
Initial integration of Passport into react-apollo-kao-example.

### PR DESCRIPTION
**Pull request by Panoplos**
Initial integration of Passport with Local, Google+, Facebook and Twitter strategies. No user management is included, but this is a good starting point.

### CODE REVIEW

**Comment by Panoplos** [comment]
Yatsu, I added the desired token expiration logic to this pull request.

**Comment by yatsu** [comment]
`Caddyfile-dev` and `Caddyfile-prod` are added again which had been removed in master.
That is probably a mistake?

**Comment by yatsu** [comment]
Oh, I see. I have just read README.

I want to make the app work without Caddy if it uses only local authentication, if it is possible...

**Comment by Panoplos** [comment]
Local Authentication actually works without Caddy, if you turn on the node dev server proxy, but the other authentication methods will not work due to some bug with (I assume) the proxy. Maybe you can figure out a way to force the React Router to cause the browser to GET `/auth/<provider>/signin`?

**Comment by yatsu** [comment]
OK. I see.

I found that `koa/auth.js` has some Flow type errors.
Can you fix that?

**Comment by Panoplos** [comment]
OK, these errors are due to use of `dotenv`. It is requiring that their existence be checked before use, but this is wonky. Should we move those constants to actual `constants.js` file?

**Comment by Panoplos** [comment]
全く別の話ですけど、お名前でわかりましたが、日本人ですね。私は日本に駐在しています。www

**Comment by yatsu** [comment]
そうだったのですね！ 私は東京にいます。

I have not noticed the `dotenv` problem.
The env vars are dynamic and could be `null`. Do we need to make them nullable and define default values?

**Comment by yatsu** [comment]
I have looked into the proxy problem.

The proxy settings are found in `react-scripts/scripts/start.js`.
The proxy middleware for Webpack looks the `Accept` header and if it is not `text/html`, redirects the request to the specified backend server.

`react-app-rewired` can modify only `config` for Webpack and cannot modify middleware.
So there is no way to change the proxy settings unless we `eject` the app from create-react-app.

Using Caddy (if social auth is required) seems to be the best way for now.

**Comment by Panoplos** [comment]
私も東京にいます。:-)

Can you please show me what errors you are getting with the flow test, because it seems the only errors I am getting are as follows: 

screen shot 2017-05-01 at 5 27 11 pm

Searching online for others that have run into this, it seems flow requires a check on these values, so something like

```es6
    ...
    password: digest(typeof process.env.USER_PASSWORD === 'string' ? process.env.USER_PASSWORD : '')
    ...
```
would work, but god is this ugly when sprinkled throughout the code! However, it is technically the "correct" thing to do. We could create a utility function that will get the `env` constants, returning a default:

```es6
// env.js
import dotenv from 'dotenv'

env = dotenv.config().parsed
env.get = (key: string, def: string): string => { env.hasOwnProperty(key) ? env[key] : def }
export env
```
Then we can just use:

```es6
  import env from './utils/env'
  ...
  password: digest(env.get('USER_PASSWORD', ''))
  ...
```
To be honest,  I am surprised that `dotenv` doesn't have a `get(key, def)` function, already.

**Comment by Panoplos** [comment]
OK, I moved the env stuff into a util that accounts for defaults. `dotenv` only parses as string values, so the type return for `env.get` is string without issue.

You can see that flow check passes now.

I had to add one `eslint-disable-next-line` in `utils.js` for "confusing arrow function", which really is kind of a ridiculous constraint, anyway.

**Comment by yatsu** [comment]
Cool! That works fine!

I have refactored a little bit. How about this?

```js
const denv = dotenv.config().parsed

export function env(key: string, def: string = ''): string {
  return denv[key] !== undefined ? denv[key] : def
}
```

You can call it as: `env('GOOGLE_CLIENT_ID')`.

**Comment by Panoplos** [comment]
Why not?

**Comment by yatsu** [comment]
OK. I will merge this PR and then rewrite `env()`.

Thank you for this PR!

**Comment by Panoplos** [comment]
Wait one minute, about to merge the env change.

**Comment by yatsu** [comment]
Any problem?

**Comment by Panoplos** [comment]
Nope, just merged your suggestion.

**Comment by yatsu** [comment]
Thank you again!

**Comment by yatsu** [comment]
Hi, @Panoplos,
I appreciate your contribution. The Passport integration works fine.

But it forces the app to use a cookie and it is a problem for me.
I need to store tokens in localStorage because I would like to make the server to work with also native apps which does not have cookies.
(I am going to add a React Native example in the future.)

So I would like to move this Passport integration to `passport` branch and inform users about it in README. If a user wants Passport and using cookies is not a problem, he can use that branch.

Is that OK?

**Comment by Panoplos** [comment]
Actually, the usage of cookies is not the passport part, but the koa session. Passport is using tokens stored in `localStorage`. However, it looks like passport is tying the the `user` object to the session ID. I think there should be a way to do sessions in koa without cookies.

**Comment by Panoplos** [comment]
Looking into React Native, it seems there should be no problem with cookies, and if there is, it is possible to use [`react-native-cookies`](https://github.com/joeferraro/react-native-cookies) library.

**Comment by Panoplos** [comment]
Also, looking at `koa-session2`, it looks it may be possible to use memcache store. Let me test this.

**Comment by yatsu** [comment]
I want to use localStorage. Is there any way to do that?

When I publish a public API, using JWT (`Authorization` header) is a popular way. You can request as `curl -H "Authorization: Bearer <token>"` and some networking libraries for mobile implements that with auto refreshing token like I have implemented in WebClient.

Handing cookies are difficult and it is a browser's technology. I think we can avoid this dependency with current technology stack.

**Comment by Panoplos** [comment]
Yes, I understand that using JWT is good, and we are using it in the current implementation for passport, but it seems like passport is internally saving the `ctx.user` in `ctx.session`. Let me do some more research into using passport without cookie based session storage.

**Comment by Panoplos** [comment]
Hey, I have figured out a way to get this working without cookies. Should be finished with the implementation by tonight.

**Comment by yatsu** [comment]
OK. I am working on `no-passport` branch until it is solved.

**Comment by Panoplos** [comment]
I have it working. Just one last issue with getting Apollo client to use the session token. Should have something up in an hour or so.

**Comment by yatsu** [comment]
I have a lot of progress in `no-passport` branch. I hope it will not be difficult to merge...

I dropped react-apollo and now the app uses redux-logic and ApolloClient to fetch/mutate.

I also implemented refreshing token and its integration tests.
* access token expired -> refreshing token automatically -> retry the last request
* refresh token expired -> automatically signed out

I want to make this available both with local and social authentication.

I have added a Apollo network interface's middleware to set `Authorization` header.

**Comment by Panoplos** [comment]
Sorry, I have been busy last 2 days setting up a new development environment. I am almost done with the implementation. Will get it working, then pull down your modifications and test.

**Comment by yatsu** [comment]
No problem at all!

I have wrapped GraphQL resolvers with the authentication function so that the authentication error will be returned as a GraphQL payload.
This works fine with the local authentication but I have no idea how to do it with Passport.
Maybe I should read and understand your next push first.

**Comment by Panoplos** [comment]
OK, I have pushed the changes (finally got some time to put into this, sorry for the delay) to my fork head, so you can see how this is implemented. I will pull your stuff down and take a look.

**Comment by yatsu** [comment]
Thank you!

Can you create a new PR?
This one is already merged.

**Pull request merged**
